apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bevel-provider-provider-endorser-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: bevel-provider-ns
spec:
  releaseName: bevel-provider-provider-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/hirex-ai/bevel
    ref: local
  values:
    metadata:
      name: bevel-provider-provider-endorser-auth-job
      namespace: bevel-provider-ns
    network:
      name: bevel
      kubernetes_url: https://192.168.59.101:8443
    image:
      name: bevel-provider
      repository: alpine:3.9.4
    vault:
      address: http://192.168.0.107:8200
      identity: provider-endorser
      admin_auth_path: kubernetes-bevel-provider-admin-auth
      policy: bevel-provider-provider-endorser-ro
      policy_content: path \"/bevel-provider/data/endorsers/provider-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-bevel-provider-provider-endorser-auth
    account:
      admin_service: bevel-provider-admin-vault-auth
      admin_role: rw
      service: bevel-provider-provider-endorser-vault-auth
      role: ro
